name: Discord Bot Deployment

on:
  push:
    branches: [ prod ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Deploy to ssh server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: 22
        passphrase: ${{ secrets.PASSPHRASE }}
        script: |
          cd ~/culture-bot
          git pull origin prod
          git status
          yarn install
          pm2 restart culture-bot